config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    get :search, on: :collection
  end
  
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    include PgSearch
    extend FriendlyId
    
    validates :title, :author, :body, presence: true
    has_many :comments, dependent: :destroy
    
    friendly_id :title, use: :slugged

    pg_search_scope :search, against: %i[title author body], associated_against: {comments: %i[body]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        comment = Comment.create!(comments_params)
        redirect_to comment.post, notice: 'Comentário enviado com sucesso!'
    end

    private

    def comments_params
        params.require(:comment).permit(:post_id, :author, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  def search
    @posts = Post.search(search_params[:q])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        #redirect_to posts_path_root(post), status: :see_other
        #flash[:success] = 'Post criado com sucesso!'
        format.html { redirect_to post_url(@post), notice: "Post criado com sucesso!" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post atualizado com sucesso!." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end

    def search_params
      params.permit(:q)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aprendendo Ruby on Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "turbo", type: "module" %>

  </head>

  <body>
    <div class="bg-primary text-white text-center mb-1 p-1">
      <%= link_to root_path, class: "text-white link-underline link-underline-opacity-0" do%>
        <h1 class="display-6" >Aprendendo Ruby on Rails</h1>
      <% end %> 
      <p class="lead">
        Aqui estará todo meu conhecimento com Ruby on Rails
      </p>

      <nav class="navbar container" id="busca">
        <div class="container-fluid busca">
          <div></div>
            <%= form_with url: search_posts_path, method: :get, local: true, class: 'form-inline d-flex' do |form| %>
              <%= form.search_field :q, class: 'form-control me-2', required: true, placeholder:'Buscar', value: params[:q] %>
              <%= form.submit 'Buscar', class: 'btn btn-success', data: {disable_with: 'Buscando...'} %>
            <% end %>
        </div>
      </nav>

    </div>

    <div class="container" >
      <% flash.each do |type,message| %>
        <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>  
    
    <footer class="bg-primary text-white text-center mt-5 p-1">
      Copyright © Bruno César <%= Date.current.year%>.
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

  <div class="form-group">
    <%= form.label :title%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :author%>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: 5 %>
  </div>

  <%= form.submit class:'btn btn-primary mt-3', data:{disable_with: 'Criando...'}  %>

<% end %>

app/views/posts/_post.html.erb
<div class="card bg-light">
  <div class="card-body">

    <h4><%= link_to post.title, post, class:"link-underline link-underline-opacity-0"%></h4>
    
    <div class="text-muted mb-2">
      <em>Por <%= post.author %> (<%= l post.created_at, format: :long %>)</em>
    </div>
    
    <%= post.body.truncate(150) %>

    <p class="text-muted" > <%= pluralize post.comments.count, 'Comentário' %></p>

    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group me-2" role="group">
        <%=link_to "Ler Artigo", post, class:"btn btn-primary"%>
      </div>
      <div class="btn-group me-2" role="group">
       <%=link_to "Editar", edit_post_path(post), class:"btn btn-secondary"%>
      </div>
      <div class="btn-group me-2" role="group">
       <%=button_to "Excluir", post, method: :delete, data: { turbo_confirm: 'Você tem certeza que deseja excluir?' }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editar post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render post%>
  <p>
  <% if Post.count > 0 %>
    <hr>
  <% end %>
<% end %>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <div class="btn btn-success">
    <%= link_to "Novo post", new_post_path, class: "text-white text-white link-underline link-underline-opacity-0"%>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Novo post</h1>

<%= render "form", post: @post %>

app/views/posts/search.html.erb
<h3 class="text-muted">
    <% if @posts.any? %>
        <%= pluralize(@posts.count,'resultado encontrado') %>
    <% else %>
        Nenhum resultado encontrado
    <% end %>
</h3>

<% @posts.each do |post| %>
  <%= render post%>
<% end %>

app/views/posts/show.html.erb
<div class="shadow bg-light p-2 rounded">

  <div class="text-center mb-5">

    <h1><%= @post.title %></h1>

    <p class="text-muted" >
      <strong>Por <%= @post.author %> </strong>
      <br>
      <%= l @post.created_at, format: :long %>
    </p>

  </div>

  <div class="px-5 mb-3" >
    <%= sanitize @post.body.gsub('\n','<br>').html_safe %>
  </div>
</div>

<div class="container shadow-sm bg-light rounded ">
  <div class="m-5" >
    <div class="text-center" >
      <h4> 
        <%= pluralize(@post.comments.count,'Comentário') %> 
        <% if @post.comments.none? %>
          <br>
          <span class="badge bg-success">Seja o primeiro a comentar!</span></span>
        <% end %>
      </h4>
    </div>

    <%= form_with model: @comment, local: true do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <div class="form-group">
        <%= form.label :author%>
        <%= form.text_field :author, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 3 %>
      </div>
    <br>
    <%= form.submit 'Comentar', class:'btn btn-primary mb-3', data:{disable_with: 'Enviando...'}  %>
    <% end %>
  </div>
</div>

<% @comments.each do |comment| %>
  <div class="container shadow-sm mb-3 bg-light rounded ">
    <div class="row">
      <div class= "col pt-3">
        <strong><%= comment.author%></strong>
      </div>
      <div class="col text-end pt-3">
        <em data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title=" <%= l comment.created_at,format: :long %> "> <%= time_ago_in_words comment.created_at%> atrás</em>
      </div>
    </div>
    <hr>
    <div class="pb-3">
      <%= sanitize comment.body.gsub('\n','<br>').html_safe%>
    </div>
  </div>  
<% end %>
</div>